# Minimal, fast defaults
line-length = 140  # More lenient to avoid mass reformatting

[lint]
select = ["E", "F", "I"]  # pycodestyle errors, pyflakes, isort
ignore = ["E501"]  # Ignore line too long for now
# Never auto-fix in CI; developers may run `ruff --fix` locally