name: CI
on:
  push: { branches: [ main, master ] }
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Core + dev deps (keep explicit so CI is deterministic)
      - name: Install deps
        run: |
          pip install -e .
          pip install fastapi uvicorn pyyaml fastmcp httpx anyio
          pip install pytest pytest-anyio ruff mypy typing-extensions

      - name: Lint (ruff)
        run: ruff --version && ruff .

      - name: Type check (mypy)
        run: mypy .

      - name: Test (pytest)
        env:
          PYTHONPATH: .
        run: pytest -q
