name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11 with pip cache
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package (editable)
        run: pip install -e .

      - name: Install runtime deps
        run: pip install fastapi uvicorn pyyaml fastmcp httpx anyio

      - name: Install dev deps (ruff, mypy, pytest, coverage)
        run: pip install ruff mypy pytest pytest-cov types-PyYAML

      - name: Lint (ruff)
        run: ruff check .

      - name: Type check (mypy)
        run: mypy src

      - name: Tests with coverage
        env:
          PYTHONPATH: .
        run: pytest -q --cov=src --cov-report=term-missing