name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install fastapi uvicorn pyyaml fastmcp httpx anyio pytest ruff mypy types-PyYAML typing_extensions
      - name: Lint (ruff)
        run: ruff check .
      - name: Type check (mypy)
        run: mypy --config-file mypy.ini .
      - name: Tests (pytest)
        env:
          PYTHONPATH: .
        run: pytest -q